Build & Deploy & Scan test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -56,6 +56,19 @@ jobs:
           command: |
             ssh -i ~/.ssh/test_key.pem azureuser@172.205.227.20 "cd /opt/lampp/htdocs/mutillidae && git pull origin main && sudo /opt/lampp/lampp restart"
 
+  check_sonar_scanner:
+    executor: machine-executor
+    steps:
+      - run:
+          name: Check SonarScanner Path
+          command: |
+            if [ ! -f /opt/sonar-scanner/bin/sonar-scanner ]; then
+              echo "SonarScanner executable not found!"
+              exit 1
+            fi
+            echo "SonarScanner executable found."
+            ls -l /opt/sonar-scanner/bin/sonar-scanner
+
   run_sonar_scanner:
     executor: machine-executor
     environment:
@@ -96,7 +109,9 @@ workflows:
       - install_sonar_scanner:
           requires:
             - deploy
-      - run_sonar_scanner:
+      - check_sonar_scanner:
           requires:
             - install_sonar_scanner
-
+      - run_sonar_scanner:
+          requires:
+            - check_sonar_scanner
